Orthogonal Vectors

In [2]:
import numpy as np

In [3]:
i = np.array([1, 0])
i

array([1, 0])

In [4]:
j=np.array([0, 1])
j

array([0, 1])

In [5]:
np.dot(i, j)  # dot product of i and j is 0 because they are orthogonal vectors

0

Orthonormal Vector

In [6]:
u = np.array([1/np.sqrt(2), 1/np.sqrt(2)])
v = np.array([-1/np.sqrt(2), 1/np.sqrt(2)])

In [7]:
print(u)
print(v)

[0.70710678 0.70710678]
[-0.70710678  0.70710678]


In [8]:
np.dot(u, v)  # dot product of u and v is 0 because they are orthogonal vectors

0.0

In [11]:
np.linalg.norm(u), np.linalg.norm(v)  # both u and v are unit vectors

(0.9999999999999999, 0.9999999999999999)

Matrices (Rank 2 Tensors) in numpy

In [3]:
x=np.array([[1, 2], [3, 4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
x.shape

(3, 2)

In [5]:
x.size

6

In [6]:
x[:,0]  # first column

array([1, 3, 5])

In [7]:
x[1,0]

3

In [9]:
x[0,:]  # first row

array([1, 2])

In [10]:
x[0:2, 0:2]  # first two rows and first two columns

array([[1, 2],
       [3, 4]])

Matrices in PyTorch

In [11]:
import torch

In [12]:
x_pt=torch.tensor(x)
x_pt

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [13]:
x_pt.shape

torch.Size([3, 2])

In [16]:
x_pt[1,:] # to get the value as a standard Python number

tensor([3, 4], dtype=torch.int32)

Matrices in Tensorflow

In [ ]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

In [ ]:
tf.rank(X_tf)

In [ ]:
tf.shape(X_tf)

In [ ]:
X_tf[1,:]