Vectors (Rank 1 Tensors) in NumPy

In [14]:
import numpy as np
import torch 
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [2]:
x=np.array([4,5,6])
x

array([4, 5, 6])

In [3]:
len(x)

3

In [4]:
x.shape

(3,)

In [5]:
type(x)

numpy.ndarray

In [6]:
x[0]

4

In [7]:
type(x[0])

numpy.int32

Vector Transportation

In [8]:
x_t=x.T
x_t

array([4, 5, 6])

In [9]:
# Same but it does we use nested "matrix-style" brackets: 
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [10]:
y.shape

(1, 3)

In [11]:
y_t=y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [12]:
# Column vector can be transposed back to original row vector: 
y_t.T 

array([[25,  2,  5]])

Zero Vectors

In [13]:
z=np.zeros(3,dtype=int)
z

array([0, 0, 0])

Vectors in Pytorch and Tensorflow

In [15]:
x_pt=torch.tensor([4,5,6])
x_pt

tensor([4, 5, 6])

In [ ]:
x_tf = tf.Variable([25, 2, 5])
x_tf