Common Tensor Operations

In [13]:
import numpy as np
import torch

In [11]:
X=([25,4],[4,5],[7,8])
X

([25, 4], [4, 5], [7, 8])

In [12]:
x_t = np.array(X).T
x_t

array([[25,  4,  7],
       [ 4,  5,  8]])

In [14]:
X_pt=torch.tensor(X) 

In [15]:
X_pt.T

tensor([[25,  4,  7],
        [ 4,  5,  8]])

In [ ]:
tf.transpose(X_tf) # less Pythonic

Basic Arithmetical Properties
Adding or multiplying with scalar applies operation to all elements and tensor shape is retained:


In [17]:
Y = np.array([[25, 2], [5, 26], [3, 7]])

In [18]:
Y*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [23]:
Y+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [24]:
Y*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [25]:
X_pt*2+2

tensor([[52, 10],
        [10, 12],
        [16, 18]])

In [26]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52, 10],
        [10, 12],
        [16, 18]])

In [ ]:
X_tf*2+2

In [ ]:
tf.add(tf.multiply(X_tf, 2), 2)

If two tensors have the same size, operations are often by default applied element-wise. This is not matrix multiplication, which we'll cover later, but is rather called the Hadamard product or simply the element-wise product.

In [27]:
Y

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [29]:
A=Y+2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [30]:
A+Y

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [31]:
A*Y

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [32]:
y_pt=torch.tensor(Y)
A_pt=y_pt+2
A_pt

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]], dtype=torch.int32)

In [33]:
A_pt*y_pt

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]], dtype=torch.int32)

In [ ]:
A_tf = X_tf + 2

In [ ]:
A_tf + X_tf

In [ ]:
A_tf * X_tf

Reduction
Calculating the sum across all elements of a tensor is a common operation.

In [34]:
Y

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [37]:
Y.sum()

68

In [39]:
torch.sum(y_pt)

tensor(68)

In [ ]:
tf.reduce_sum(X_tf)

In [41]:
# Can also be done along one specific axis alone, e.g.:
Y.sum(axis=0) # summing over all rows

array([33, 35])

In [42]:
Y.sum(axis=1)

array([27, 31, 10])

In [43]:
torch.sum(y_pt, axis=0) # summing over all rows

tensor([33, 35])

In [ ]:
tf.reduce_sum(X_tf, 1)

Many other operations can be applied with reduction along all or a selection of axes, e.g.:

1.maximum
2.minimum
3.mean
4.product

DOT PRODUCT

- The dot product (also called the inner product) is a fundamental operation in linear algebra, widely used in machine learning.
- For two vectors of the same length, the dot product is the sum of the products of their corresponding elements.
- In matrix notation, the dot product of vectors **a** and **b** is written as:  
    **a · b = Σ aᵢbᵢ**
- The dot product measures the similarity between two vectors; a higher value indicates greater alignment.
- In neural networks, dot products are used to compute weighted sums in layers.
- The dot product is used in calculating projections, cosine similarity, and in optimization algorithms.
- For matrices, the dot product generalizes to matrix multiplication, which is essential for transforming data and weights in machine learning models.
- The result of a dot product is a scalar (for vectors) or another matrix (for matrices).
- The dot product is commutative for real-valued vectors: **a · b = b · a**.

In [57]:
a=np.array([25,2,3])

In [54]:
z=np.array([1,2,3])
z
z.shape

(3,)

In [55]:
25*1+2*2+3*3

38

In [58]:
np.dot( a,z)

38

In [59]:
a_pt=torch.tensor(a)

In [60]:
z_pt = torch.tensor([0, 1, 2])
z_pt

tensor([0, 1, 2])

In [62]:
np.dot(a_pt, z_pt)

8

In [63]:
torch.dot(torch.tensor([25, 2, 5.]), torch.tensor([0, 1, 2.]))

tensor(12.)

In [ ]:
x_tf

In [ ]:
y_tf = tf.Variable([0, 1, 2])
y_tf

In [ ]:
tf.reduce_sum(tf.multiply(x_tf, y_tf))