L^2 Norm

In [3]:
import numpy as np

In [4]:
x=np.array([3,4,6])
x

array([3, 4, 6])

In [5]:
(3**2+4**2+6**2)**0.5

7.810249675906654

In [6]:
np.linalg.norm(x)

7.810249675906654

L^1 norm

In [7]:
x

array([3, 4, 6])

In [8]:
np.abs(3)+np.abs(4)+np.abs(6)

13

Squared L^2 norm

In [9]:
(3**2+4**2+6**2)

61

In [10]:
np.dot(x,x)

61

Max norm

In [11]:
x

array([3, 4, 6])

In [12]:
np.max([np.abs(3),np.abs(4),np.abs(6)])

6